### ISSUE TITLE
Implementing multi-head value,  policy networks and using act-experience-update workflow

### ISSUE THREAD

**Issue by vermashresth** [tensorforce/tensorforce#707] opened 2020-06-18 17:44 UTC
Hi @AlexKuhnle
I have recently started using the `independent_act - experience - update` workflow for training agents and I really like the flexibility it offers. However, I have certain doubts about implementing one of my use cases.

I am trying to have a multi-head network with several policy and value heads. The output policy distribution is given as the average of all policy heads and same is the case with value function. But losses are accumulated for all the heads separately and combined loss is optimized. (Interestingly, such a setup allows measuring epistemic uncertainty in agent's actions ([paper](https://www.aaai.org/Papers/AAAI/2020GB/AAAI-SilvaF.2159.pdf)))

In particular, I have the following questions:
1. When calling `agent.act`,  for say ProximalPolicyOptimization based agent, is it possible to access the value function output? I noticed that passing query for `action-distribution-probabilities` returns policy action distribution but no query exists for accessing value function during `act`.
2. How to pass a custom network in the agent definition? Is multi-head architecture possible by the dictionary-based representation? I tried searching for custom network definition in the docs but couldn't find it.
3. Is custom action selection possible based on averaging of policy heads?
4. Is it possible to define a custom loss function?

I believe a lot of this can be implemented without much work if sharing base layers between different agents can somehow be possible.

I would be happy to contribute if some of these features would be useful for multiple use cases!

**Comment by AlexKuhnle** [comment] 2020-06-19 08:44
Hi,

Good to hear the act-experience-update workflow proves useful. Maybe there should be more in the docs on that. Also, if you happen to have a little toy example script, feel free to add it to the examples folder... :-)

Regarding your questions:
1. It would be possible to add this, these named tensors were added as requested. However, note that this feature will unfortunately be dropped with the next version, at least for now, since the current implementation seems not compatible with TF2. However, at least for eager mode with TF2 it's quite easy to just output tensors in the middle of the code, so possible to get something similar back soon.
2. There's some (minimal) information [here](https://tensorforce.readthedocs.io/en/latest/basics/agent-specification.html) and [here](https://tensorforce.readthedocs.io/en/latest/basics/features.html). But from what I understand, you want to modify both network and in particular the last distribution layer (Tensorforce "network" == network minus last layer :-). That may require a bit more customization. See next point.
3. I think it may be easiest to implement a custom `Distribution` object, or maybe `Policy`. Are the heads just the last layers, or do they involve more? For instance, a multi-head categorical distribution class could just wrap multiple categorical instances and return averages etc accordingly.
4. Yes, in principle it is, depends a bit on what the loss function involves.

I think it all comes down to the question: are the multi-heads just final layer(s) which share a main policy network, or is there more? For instance, in the end you mention "multiple agents" -- what does that mean?

**Comment by vermashresth** [comment] 2020-06-22 01:10
Hi @AlexKuhnle ,
Thank you for your detailed reply. Yes, I think splitting heads only at the last layer should be fine. 

I tried implementing a custom `Policy` that you suggested but couldn't succeed with that. Could you provide a minimal script of how would one go about it? 

Regarding the multiple agents, I was hoping if instead of having a single agent with multiple output heads and writing a custom loss function, we could have multiple agents, all sharing the base layers and each one independently minimizing their predefined loss function (which would internally update the base layers because they have shared weights). I am not sure though if that is possible and whether it would give the same result as a multi-head network.

I think it would be really nice if we could add some example scripts on customizing various modules in Tensorforce. And sure, I will make a PR for adding a toy example for the `act-experience-update`  workflow!

**Comment by AlexKuhnle** [comment] 2020-06-22 14:44
It sounds to me like you could just define a "ensemble distribution" which wraps multiple internal distribution instances and averages outputs accordingly (see e.g. the [categorical distr](https://github.com/tensorforce/tensorforce/blob/master/tensorforce/core/distributions/distribution.py) for what a distribution does). You just need to create the distribution modules as part of your new ensemble distribution and each of the functions needs to forward input arguments to every distr in the ensemble, collect the outputs and average them. Isn't that roughly what you want to set up?

**Comment by AlexKuhnle** [comment] 2020-06-24 20:47
A little more detail:  If you update the shared weights based on multiple agents using e.g. the PG loss `R * log pi(a|s)`, that should be roughly the same as `1/? * R * sum( log pi_k(a|s) )`, which is the same as `R * log pi(a|s)` where `pi(a|s) = prod( pi_k(a|s) )` is an ensemble and `1/?` some normalization constant (can be ignored / collapsed with learning rate). Does that sound reasonable? So the ensemble distribution just averages the log-probs of multiple distribution heads. That shouldn't be problematic to implement.

**Comment by vermashresth** [comment] 2020-07-08 09:37
Hi @AlexKuhnle 

Thank you for your inputs and I'm sorry for replying late.

Your suggestion does sound reasonable and I have somewhat been able to replicate this setup using an ensemble distribution as you mentioned.
On the other hand, I am stuck at implementing the `act-experience-update` workflow. Earlier, I had only worked with single-step games but with environments having multiple time-steps, I can't figure out why this error is showing up.
Here's a script to replicate the error.
```python
from tensorforce.agents import Agent
from tensorforce.environments import Environment
environment = Environment.create(environment='gym', level='CartPole-v1')
agent = Agent.create(
        agent='ppo', environment=environment,
        network='auto',
        batch_size=5
    )
states = environment.reset()
actions = agent.act(states=states, independent=True)
states, terminal, reward = environment.execute(actions=actions)
agent.experience(states = [states]*5, actions = [actions]*5, terminal=[0,0, 0, 0, 1], reward = [10]*5)
agent.update()
```
The error trace is long
```
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

14 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
-> 1350                                       target_list, run_metadata)
   1351 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1442                                             fetch_list, target_list,
-> 1443                                             run_metadata)
   1444 

InvalidArgumentError: assertion failed: [Agent.experience: invalid shape for action_mask action-mask input.] [Condition x == y did not hold element-wise:] [x (agent.experience/Shape_4:0) = ] [1 2] [y (agent.experience/concat_1:0) = ] [5 2]
	 [[{{node agent.experience/assert_equal_9/Assert/Assert}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-16-cae5e0e24779> in <module>()
     10 actions = agent.act(states=states, independent=True)
     11 states, terminal, reward = environment.execute(actions=actions)
---> 12 agent.experience(states = [states]*5, actions = [actions]*5, terminal=[0,0, 0, 0, 1], reward = [10]*5)
     13 agent.update()

/content/tensorforce/tensorforce/agents/tensorforce.py in experience(self, states, actions, terminal, reward, internals, query, **kwargs)
    419                     states=states_batch, internals=internals_batch,
    420                     auxiliaries=auxiliaries_batch, actions=actions_batch, terminal=terminal_batch,
--> 421                     reward=reward_batch, **kwargs
    422                 )
    423 

/content/tensorforce/tensorforce/core/module.py in fn(query, **kwargs)
    660 
    661             # TensorFlow session call
--> 662             fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
    663 
    664             return fetched

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
    776         feed_dict=feed_dict,
    777         options=options,
--> 778         run_metadata=run_metadata)
    779 
    780   def run_step_fn(self, step_fn):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1382         raise six.reraise(*original_exc_info)
   1383       else:
-> 1384         raise six.reraise(*original_exc_info)
   1385 
   1386 

/usr/local/lib/python3.6/dist-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1367   def run(self, *args, **kwargs):
   1368     try:
-> 1369       return self._sess.run(*args, **kwargs)
   1370     except _PREEMPTION_ERRORS:
   1371       raise

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1440         feed_dict=feed_dict,
   1441         options=options,
-> 1442         run_metadata=run_metadata)
   1443 
   1444     for hook in self._hooks:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1198 
   1199   def run(self, *args, **kwargs):
-> 1200     return self._sess.run(*args, **kwargs)
   1201 
   1202   def run_step_fn(self, step_fn, raw_session, run_with_hooks):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    956     try:
    957       result = self._run(None, fetches, feed_dict, options_ptr,
--> 958                          run_metadata_ptr)
    959       if run_metadata:
    960         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1179     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1180       results = self._do_run(handle, final_targets, final_fetches,
-> 1181                              feed_dict_tensor, options, run_metadata)
   1182     else:
   1183       results = []

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:
   1361       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InvalidArgumentError: assertion failed: [Agent.experience: invalid shape for action_mask action-mask input.] [Condition x == y did not hold element-wise:] [x (agent.experience/Shape_4:0) = ] [1 2] [y (agent.experience/concat_1:0) = ] [5 2]
	 [[node agent.experience/assert_equal_9/Assert/Assert (defined at /content/tensorforce/tensorforce/core/models/tensorforce.py:405) ]]

Errors may have originated from an input operation.
Input Source operations connected to node agent.experience/assert_equal_9/Assert/Assert:
 agent.experience/Shape_4 (defined at /content/tensorforce/tensorforce/core/models/tensorforce.py:402)	
 agent.experience/concat_1 (defined at /content/tensorforce/tensorforce/core/models/tensorforce.py:403)
```

Also, something like this works fine
```python
agent.experience(states = [states]*5, actions = [actions]*5, terminal=[1,1,1,1,1], reward = [10]*5)
agent.update()
```

**Comment by AlexKuhnle** [comment] 2020-07-08 11:38
I don't see what is wrong here from your side, so it is probably a bug in the framework. Thanks for the example to reproduce the problem, will look into it soon. Are you on `master` or `tf2` branch? (Past time these are merged...)

**Comment by vermashresth** [comment] 2020-07-08 14:46
@AlexKuhnle  I installed it from the latest master branch.
Also, I forgot to mention, passing a single data point as a batch in the `agent.experience` and then calling `agent.update` also throws an error. (continuing from the previous example)
```python
agent.experience(states = states, actions = actions, terminal=1, reward = 10)
agent.update()
```
or 
```python
agent.experience(states = [states], actions = [actions], terminal=[1], reward = [10])
agent.update()
```
Error trace
```
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

14 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
-> 1350                                       target_list, run_metadata)
   1351 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1442                                             fetch_list, target_list,
-> 1443                                             run_metadata)
   1444 

InvalidArgumentError: Need minval < maxval, got 0 >= 0
	 [[{{node inner-optimizer.step/random_uniform}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-6-97bee0152c43> in <module>()
     11 states, terminal, reward = environment.execute(actions=actions)
     12 agent.experience(states = states, actions = actions, terminal=1, reward = 10)
---> 13 agent.update()

/content/tensorforce/tensorforce/agents/tensorforce.py in update(self, query, **kwargs)
    443         # Model.update()
    444         if query is None:
--> 445             self.timesteps, self.episodes, self.updates = self.model.update(**kwargs)
    446 
    447         else:

/content/tensorforce/tensorforce/core/module.py in fn(query, **kwargs)
    660 
    661             # TensorFlow session call
--> 662             fetched = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
    663 
    664             return fetched

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
    776         feed_dict=feed_dict,
    777         options=options,
--> 778         run_metadata=run_metadata)
    779 
    780   def run_step_fn(self, step_fn):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1382         raise six.reraise(*original_exc_info)
   1383       else:
-> 1384         raise six.reraise(*original_exc_info)
   1385 
   1386 

/usr/local/lib/python3.6/dist-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1367   def run(self, *args, **kwargs):
   1368     try:
-> 1369       return self._sess.run(*args, **kwargs)
   1370     except _PREEMPTION_ERRORS:
   1371       raise

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1440         feed_dict=feed_dict,
   1441         options=options,
-> 1442         run_metadata=run_metadata)
   1443 
   1444     for hook in self._hooks:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1198 
   1199   def run(self, *args, **kwargs):
-> 1200     return self._sess.run(*args, **kwargs)
   1201 
   1202   def run_step_fn(self, step_fn, raw_session, run_with_hooks):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    956     try:
    957       result = self._run(None, fetches, feed_dict, options_ptr,
--> 958                          run_metadata_ptr)
    959       if run_metadata:
    960         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1179     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1180       results = self._do_run(handle, final_targets, final_fetches,
-> 1181                              feed_dict_tensor, options, run_metadata)
   1182     else:
   1183       results = []

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:
   1361       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InvalidArgumentError: Need minval < maxval, got 0 >= 0
	 [[{{node inner-optimizer.step/random_uniform}}]]
```

**Comment by AlexKuhnle** [comment] 2020-07-11 19:08
Hey, sorry for coming back to this a bit late. I've moved version 0.6 beta to master now, and for this version your code snippets seem to run without problems. So I would recommend updating to the new version. Apart from a few argument names (see update notes), the transition should hopefully not be a problem, but let me know if there are problems.

**Comment by vermashresth** [comment] 2020-07-20 21:20
Thanks @AlexKuhnle, the code snippets do work now. However, for the same configuration, training with the `act-experience-update` API doesn't seem to converge but `act-observe` works fine. Here's an example

```python
from tensorforce.agents import Agent
from tensorforce.environments import Environment

environment = Environment.create(environment='gym', level='CartPole-v1')
agent = Agent.create(
        agent='ppo', environment=environment,
        batch_size=10
    )

n_episodes = 200
update_frequency = 10

for ep in range(n_episodes):
  states = environment.reset()
  ep_reward = 0
  terminal = False
  
  while not terminal:
    actions = agent.act(states=states, independent=True)
    states, terminal, reward = environment.execute(actions=actions)
    agent.experience(states=states, actions=actions, reward=reward, terminal=terminal)
    ep_reward += reward

  if ep%update_frequency==0:
    agent.update()
    print("ep {}, rew {}".format(ep, ep_reward))

```
`act-observe`
```python
for ep in range(n_episodes):
  states = environment.reset()
  ep_reward = 0
  terminal = False
  
  while not terminal:
    actions = agent.act(states=states, independent=False)
    states, terminal, reward = environment.execute(actions=actions)
    agent.observe(reward=reward, terminal=terminal)
    ep_reward += reward
  
  if ep%update_frequency==0:
    print("ep {}, rew {}".format(ep, ep_reward))
```

I also tried changing the update frequency, giving batches in experience and explicitly using an epsilon greedy action selection but none seem to work. Is there something I am missing here?

**Comment by AlexKuhnle** [comment] 2020-07-21 17:18
I can't see an obvious problem, so I would think that the example should work. Will have a look soon...

**Comment by AlexKuhnle** [comment] 2020-07-21 21:10
Thanks for providing the minimal example, very helpful. I'm pretty sure there is a bug, and I assume it's related to the internal reward estimation. (There is a question whether one wants to assume that the `experience` input are "expert demonstration" which should be left as is, or whether it's just raw `experience` -- the latter should be the case for the current `experience` implementation, but this may have caused the mismatch. Plus, there should be a separate expert demo feed function.)

I may take a few days to fix it, so just to let you know.

**Comment by AlexKuhnle** [comment] 2020-08-14 13:07
Sorry for the very late response. Finally found that the reason for this was, on the one hand, that independent act did not apply sampling (fixed in latest commit, probably requires additional `deterministic` argument in the future) and, on the other hand, that `experience` requires an entire episode to be fed (still need to add an exception for invalid inputs):

```python
for ep in range(1, n_episodes):
    states = environment.reset()
    ep_reward = 0
    terminal = False

    states_list = list()
    actions_list = list()
    terminal_list = list()
    reward_list = list()
    while not terminal:
        states_list.append(states)
        actions = agent.act(states=states, independent=True)
        actions_list.append(actions)
        next_states, terminal, reward = environment.execute(actions=actions)
        terminal_list.append(terminal)
        reward_list.append(reward)
        # agent.experience(states=states, actions=actions, reward=reward, terminal=terminal)
        states = next_states
        ep_reward += reward
    agent.experience(states=states_list, actions=actions_list, reward=reward_list, terminal=terminal_list)
```

This code should work now. I will also add an example soon. I think this issue can be closed then. Sorry again for the delay -- didn't manage to find the problem initially, then got distracted for a while. :-/

**Closed** 2020-08-14 13:07 UTC
